import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Icons } from "@/components/icons";
import { ModeToggle } from "@/components/mode-toggle";
import { PostHogProvider } from "@/components/post-hog-provider";
import { TextLink } from "@/components/text-link";
import { Button } from "@/components/ui/button";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-col items-center justify-center fixed top-4 right-4 z-50 bg-muted/50 rounded-full p-1">
            <ModeToggle />
            <Button className="h-7 w-7" size="icon" variant="ghost" asChild>
              <a href="https://github.com/Jacksonmills/jem-ui">
                <Icons.gitHub className="w-6 h-6" />
              </a>
            </Button>
          </div>
          <div className="isolate">
            <PostHogProvider>
              <div className="max-w-3xl mx-auto flex flex-col min-h-svh px-4 py-8 gap-8">
                <header className="flex flex-col gap-1">
                  <h1 className="text-3xl font-bold tracking-tight">JEM/UI</h1>
                  <p className="text-muted-foreground">
                    A component registry built with{" "}
                    <TextLink href="https://base-ui.com/">Base UI</TextLink>{" "}
                    primitives and powered by{" "}
                    <TextLink href="https://ui.shadcn.com/">shadcn</TextLink>.
                  </p>
                </header>
                {children}
                <footer className="text-muted-foreground text-sm p-4 border-t-2 border-dotted">
                  Built by{" "}
                  <TextLink href="https://twitter.com/jacksonmills">
                    JEM
                  </TextLink>
                  . The source code is available on{" "}
                  <TextLink href="https://github.com/Jacksonmills/jem-ui">
                    GitHub
                  </TextLink>
                  .
                </footer>
              </div>
            </PostHogProvider>
          </div>
        </ThemeProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
